services:
  app:
    container_name: api-backend
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/posecommerce
  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: posecommerce
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: