/// Permissions: (code, description)
/// Format: module:action
pub const PERMISSIONS: &[(&str, &str)] = &[
    // Identity module permissions
    ("users:create", "Create new users"),
    ("users:read", "View user information"),
    ("users:update", "Update user information"),
    ("users:delete", "Delete users"),
    ("users:list", "List all users"),
    ("roles:create", "Create new roles"),
    ("roles:read", "View role information"),
    ("roles:update", "Update role information"),
    ("roles:delete", "Delete roles"),
    ("roles:list", "List all roles"),
    ("roles:assign_permissions", "Assign permissions to roles"),
    ("permissions:read", "View permission information"),
    ("permissions:list", "List all permissions"),
    // Store management permissions
    ("stores:create", "Create new stores"),
    ("stores:read", "View store information"),
    ("stores:update", "Update store information"),
    ("stores:delete", "Delete stores"),
    ("stores:list", "List all stores"),
    ("stores:assign_users", "Assign users to stores"),
    // Product management permissions
    ("products:create", "Create new products"),
    ("products:read", "View product information"),
    ("products:update", "Update product information"),
    ("products:delete", "Delete products"),
    ("products:list", "List all products"),
    ("variants:create", "Create product variants"),
    ("variants:read", "View product variants"),
    ("variants:update", "Update product variants"),
    ("variants:delete", "Delete product variants"),
    ("recipes:create", "Create product recipes"),
    ("recipes:read", "View product recipes"),
    ("recipes:update", "Update product recipes"),
    ("recipes:delete", "Delete product recipes"),
    ("recipes:calculate_cost", "Calculate recipe costs"),
    // Inventory module permissions
    ("inventory:read", "View inventory levels"),
    ("inventory:write", "Create inventory stocks"),
    ("inventory:update", "Update inventory levels"),
    ("inventory:transfer", "Transfer inventory between stores"),
    (
        "inventory:adjust",
        "Create and manage inventory adjustments",
    ),
    (
        "inventory:approve_adjustments",
        "Approve inventory adjustments",
    ),
    ("inventory:reserve", "Create inventory reservations"),
    ("reservations:create", "Create inventory reservations"),
    ("reservations:read", "View reservations"),
    ("reservations:confirm", "Confirm reservations"),
    ("reservations:cancel", "Cancel reservations"),
    ("reservations:expire", "Expire pending reservations"),
    ("adjustments:create", "Create inventory adjustments"),
    ("adjustments:read", "View inventory adjustments"),
    ("adjustments:submit", "Submit adjustments for approval"),
    ("adjustments:approve", "Approve inventory adjustments"),
    ("adjustments:reject", "Reject inventory adjustments"),
    (
        "adjustments:apply",
        "Apply approved adjustments to inventory",
    ),
    ("transfers:create", "Create stock transfers"),
    ("transfers:read", "View stock transfers"),
    ("transfers:ship", "Ship stock transfers"),
    ("transfers:receive", "Receive stock transfers"),
    ("transfers:cancel", "Cancel stock transfers"),
    ("categories:create", "Create product categories"),
    ("categories:read", "View product categories"),
    ("categories:update", "Update product categories"),
    ("categories:delete", "Delete product categories"),
    ("categories:list", "List all categories"),
    // Sales module permissions
    ("sales:create", "Create sales transactions"),
    ("sales:update", "Update sales transactions"),
    ("sales:process_payment", "Process payments for sales"),
    ("sales:apply_discount", "Apply discounts to sales"),
    ("sales:read", "View sales transactions"),
    ("sales:void", "Void sales transactions"),
    ("sales:list", "List sales transactions"),
    ("sales:complete", "Complete sales transactions"),
    ("sales:reports", "View sales reports"),
    ("sales:manage_cart", "Manage shopping carts"),
    ("sales:manage_credit_note", "Manage credit notes"),
    ("sales:manage_shift", "Manage cashier shifts"),
    ("sales:read_shift", "View cashier shift details"),
    ("sales:approve_credit_note", "Approve credit notes"),
    ("sales:read_credit_note", "View credit note details"),
    ("sales:create_customer", "Create customers"),
    ("sales:read_customer", "View customer information"),
    ("sales:update_customer", "Update customer information"),
    // Promotions module permissions
    ("promotions:create", "Create promotions"),
    ("promotions:read", "View promotions"),
    ("promotions:update", "Update promotions"),
    ("promotions:apply", "Apply promotions to sales"),
    // E-commerce order workflow permissions
    ("orders:mark_paid", "Mark e-commerce order as paid"),
    ("orders:process", "Start processing an e-commerce order"),
    ("orders:ship", "Ship an e-commerce order"),
    ("orders:deliver", "Mark e-commerce order as delivered"),
    ("orders:cancel", "Cancel an e-commerce order"),
    // Purchasing module permissions
    ("vendors:create", "Create new vendors/suppliers"),
    ("vendors:read", "View vendor information"),
    ("vendors:update", "Update vendor information"),
    ("purchase_orders:create", "Create purchase orders"),
    ("purchase_orders:read", "View purchase order details"),
    ("purchase_orders:update", "Update draft purchase orders"),
    (
        "purchase_orders:submit",
        "Submit purchase orders for approval",
    ),
    (
        "purchase_orders:approve",
        "Approve or reject purchase orders",
    ),
    ("purchase_orders:cancel", "Cancel purchase orders"),
    ("purchase_orders:close", "Close completed purchase orders"),
    ("goods_receipts:create", "Create goods receipts"),
    ("goods_receipts:read", "View goods receipt details"),
    ("goods_receipts:confirm", "Confirm goods receipts"),
    ("goods_receipts:cancel", "Cancel goods receipts"),
    // Fiscal module permissions
    ("invoices:create", "Generate fiscal invoices"),
    ("invoices:read", "View fiscal invoices"),
    ("invoices:void", "Void fiscal invoices"),
    ("invoices:report", "Generate fiscal reports"),
    ("tax_rates:create", "Create tax rates"),
    ("tax_rates:read", "View tax rates"),
    ("tax_rates:update", "Update tax rates"),
    ("tax_rates:delete", "Delete tax rates"),
    // Payments module permissions
    (
        "payment_gateways:read",
        "View payment gateway configuration",
    ),
    (
        "payment_gateways:create",
        "Create payment gateway (super_admin only)",
    ),
    (
        "payment_gateways:update",
        "Update payment gateway (super_admin only)",
    ),
    (
        "payment_gateways:delete",
        "Delete payment gateway (super_admin only)",
    ),
    ("transactions:create", "Process online payment transactions"),
    ("transactions:read", "View payment transactions"),
    ("transactions:refund", "Refund payment transactions"),
    (
        "transactions:confirm",
        "Manually confirm/reject pending payment transactions",
    ),
    (
        "transactions:reconcile",
        "Reconcile payment transactions against gateway",
    ),
    ("payouts:read", "View gateway payouts/settlements"),
    // Shipping module permissions
    (
        "shipping:read",
        "Read shipping configuration (methods/zones/rates)",
    ),
    ("shipping:create", "Create shipping methods/zones/rates"),
    ("shipping:update", "Update shipping methods/zones/rates"),
    ("shipping:delete", "Delete shipping methods/zones/rates"),
    ("shipments:read", "Read shipments"),
    ("shipments:create", "Create shipments"),
    ("shipments:update", "Update shipment status / tracking"),
    (
        "shipments:assign",
        "Assign / reassign drivers / dispatch providers",
    ),
    ("shipments:cancel", "Cancel shipments"),
    ("drivers:read", "Read drivers"),
    ("drivers:create", "Create drivers"),
    ("drivers:update", "Update drivers"),
    ("drivers:delete", "Delete drivers"),
    (
        "delivery_providers:read",
        "Read delivery provider configuration",
    ),
    (
        "delivery_providers:create",
        "Create delivery provider (super_admin only)",
    ),
    (
        "delivery_providers:update",
        "Update delivery provider (super_admin only)",
    ),
    (
        "delivery_providers:delete",
        "Delete delivery provider (super_admin only)",
    ),
    // Catalog module permissions
    (
        "catalog:read",
        "Read product listings, images, approved reviews, wishlist",
    ),
    ("catalog:create", "Create product listings"),
    (
        "catalog:update",
        "Update listings, manage images, publish/unpublish",
    ),
    ("catalog:delete", "Delete listings"),
    ("catalog:review", "Submit product reviews (customer)"),
    ("catalog:moderate", "Approve / delete reviews (manager+)"),
    (
        "image_storage_providers:read",
        "Read image storage configuration",
    ),
    (
        "image_storage_providers:create",
        "Create image storage provider (super_admin only)",
    ),
    (
        "image_storage_providers:update",
        "Update image storage provider (super_admin only)",
    ),
    (
        "image_storage_providers:delete",
        "Delete image storage provider (super_admin only)",
    ),
    // Reports permissions
    ("reports:sales", "Access sales reports"),
    ("reports:inventory", "Access inventory reports"),
    ("reports:inventory_history", "Access history stock reports"),
    (
        "reports:inventory_valuation",
        "Access inventory valuation reports",
    ),
    ("reports:inventory_low_stock", "Access low stock reports"),
    ("reports:purchases", "Access purchasing reports"),
    ("reports:financial", "Access financial reports"),
    // System permissions
    (
        "system:admin",
        "Full system administration access (super_admin only)",
    ),
    ("system:settings", "Manage system settings"),
    ("system:audit_log", "View audit logs"),
    ("system:backup", "Manage system backups"),
    // E-commerce customer permissions
    ("cart:view", "View shopping cart"),
    ("cart:add", "Add items to shopping cart"),
    ("cart:update", "Update cart item quantities"),
    ("cart:remove", "Remove items from shopping cart"),
    ("cart:checkout", "Proceed to checkout"),
    ("orders:create", "Place orders"),
    ("orders:view_own", "View own order history"),
    ("orders:cancel_own", "Cancel own pending orders"),
    ("profile:view", "View own profile"),
    ("profile:update", "Update own profile information"),
    ("wishlist:manage", "Manage product wishlist"),
    ("reviews:create", "Create product reviews"),
    ("reviews:view", "View product reviews"),
];

/// Roles: (name, description, is_system_protected)
pub const ROLES: &[(&str, &str, bool)] = &[
    (
        "super_admin",
        "Full system access with all permissions",
        true,
    ),
    ("store_admin", "Full access to a specific store", true),
    (
        "store_manager",
        "Manage store operations, inventory, and staff",
        true,
    ),
    (
        "cashier",
        "Process sales and handle customer transactions",
        true,
    ),
    ("inventory_clerk", "Manage inventory and stock levels", true),
    (
        "purchasing_agent",
        "Create and manage purchase orders",
        false,
    ),
    ("viewer", "Read-only access to store data", false),
    (
        "customer",
        "E-commerce customer with access to shopping cart, orders, profile, and product browsing",
        false,
    ),
];

/// Role permissions mapping: (role_name, &[permission_codes])
pub const ROLE_PERMISSIONS: &[(&str, &[&str])] = &[
    // Super admin gets all permissions
    (
        "super_admin",
        &[
            // Identity
            "users:create",
            "users:read",
            "users:update",
            "users:delete",
            "users:list",
            "roles:create",
            "roles:read",
            "roles:update",
            "roles:delete",
            "roles:list",
            "roles:assign_permissions",
            "permissions:read",
            "permissions:list",
            // Stores
            "stores:create",
            "stores:read",
            "stores:update",
            "stores:delete",
            "stores:list",
            "stores:assign_users",
            // Products
            "products:create",
            "products:read",
            "products:update",
            "products:delete",
            "products:list",
            "variants:create",
            "variants:read",
            "variants:update",
            "variants:delete",
            "recipes:create",
            "recipes:read",
            "recipes:update",
            "recipes:delete",
            "recipes:calculate_cost",
            // Inventory
            "inventory:read",
            "inventory:write",
            "inventory:update",
            "inventory:transfer",
            "inventory:adjust",
            "inventory:approve_adjustments",
            "inventory:reserve",
            "reservations:create",
            "reservations:read",
            "reservations:confirm",
            "reservations:cancel",
            "reservations:expire",
            "adjustments:create",
            "adjustments:read",
            "adjustments:submit",
            "adjustments:approve",
            "adjustments:reject",
            "adjustments:apply",
            "transfers:create",
            "transfers:read",
            "transfers:ship",
            "transfers:receive",
            "transfers:cancel",
            "categories:create",
            "categories:read",
            "categories:update",
            "categories:delete",
            "categories:list",
            // Sales
            "sales:create",
            "sales:read",
            "sales:update",
            "sales:void",
            "sales:list",
            "sales:complete",
            "sales:reports",
            "sales:process_payment",
            "sales:apply_discount",
            "sales:create_customer",
            "sales:read_customer",
            "sales:update_customer",
            "sales:manage_shift",
            "sales:read_shift",
            "sales:manage_cart",
            "sales:manage_credit_note",
            "sales:read_credit_note",
            "sales:approve_credit_note",
            // Promotions
            "promotions:create",
            "promotions:read",
            "promotions:update",
            "promotions:apply",
            // E-commerce orders
            "orders:mark_paid",
            "orders:process",
            "orders:ship",
            "orders:deliver",
            "orders:cancel",
            // Purchasing
            "vendors:create",
            "vendors:read",
            "vendors:update",
            "purchase_orders:create",
            "purchase_orders:read",
            "purchase_orders:update",
            "purchase_orders:submit",
            "purchase_orders:approve",
            "purchase_orders:cancel",
            "purchase_orders:close",
            "goods_receipts:create",
            "goods_receipts:read",
            "goods_receipts:confirm",
            "goods_receipts:cancel",
            // Fiscal
            "invoices:create",
            "invoices:read",
            "invoices:void",
            "invoices:report",
            "tax_rates:create",
            "tax_rates:read",
            "tax_rates:update",
            "tax_rates:delete",
            // Payments
            "payment_gateways:read",
            "payment_gateways:create",
            "payment_gateways:update",
            "payment_gateways:delete",
            "transactions:create",
            "transactions:read",
            "transactions:refund",
            "transactions:confirm",
            "transactions:reconcile",
            "payouts:read",
            // Shipping
            "shipping:read",
            "shipping:create",
            "shipping:update",
            "shipping:delete",
            "shipments:read",
            "shipments:create",
            "shipments:update",
            "shipments:assign",
            "shipments:cancel",
            "drivers:read",
            "drivers:create",
            "drivers:update",
            "drivers:delete",
            "delivery_providers:read",
            "delivery_providers:create",
            "delivery_providers:update",
            "delivery_providers:delete",
            // Catalog
            "catalog:read",
            "catalog:create",
            "catalog:update",
            "catalog:delete",
            "catalog:review",
            "catalog:moderate",
            "image_storage_providers:read",
            "image_storage_providers:create",
            "image_storage_providers:update",
            "image_storage_providers:delete",
            // Reports
            "reports:sales",
            "reports:inventory",
            "reports:inventory_history",
            "reports:inventory_valuation",
            "reports:inventory_low_stock",
            "reports:purchases",
            "reports:financial",
            // System
            "system:admin",
            "system:settings",
            "system:audit_log",
            "system:backup",
        ],
    ),
    // Store admin - full store access
    (
        "store_admin",
        &[
            // Identity
            "users:create",
            "users:read",
            "users:update",
            "users:list",
            "roles:read",
            "roles:list",
            "permissions:read",
            "permissions:list",
            // Stores
            "stores:read",
            "stores:update",
            "stores:assign_users",
            // Products
            "products:create",
            "products:read",
            "products:update",
            "products:delete",
            "products:list",
            "variants:create",
            "variants:read",
            "variants:update",
            "variants:delete",
            "recipes:create",
            "recipes:read",
            "recipes:update",
            "recipes:delete",
            "recipes:calculate_cost",
            // Inventory
            "inventory:read",
            "inventory:write",
            "inventory:update",
            "inventory:transfer",
            "inventory:adjust",
            "inventory:approve_adjustments",
            "inventory:reserve",
            "reservations:create",
            "reservations:read",
            "reservations:confirm",
            "reservations:cancel",
            "adjustments:create",
            "adjustments:read",
            "adjustments:submit",
            "adjustments:approve",
            "adjustments:reject",
            "adjustments:apply",
            "transfers:create",
            "transfers:read",
            "transfers:ship",
            "transfers:receive",
            "transfers:cancel",
            "categories:create",
            "categories:read",
            "categories:update",
            "categories:delete",
            "categories:list",
            // Sales
            "sales:create",
            "sales:read",
            "sales:update",
            "sales:void",
            "sales:list",
            "sales:complete",
            "sales:reports",
            "sales:process_payment",
            "sales:apply_discount",
            "sales:create_customer",
            "sales:read_customer",
            "sales:update_customer",
            "sales:manage_shift",
            "sales:read_shift",
            "sales:manage_cart",
            "sales:manage_credit_note",
            "sales:read_credit_note",
            "sales:approve_credit_note",
            // Promotions
            "promotions:create",
            "promotions:read",
            "promotions:update",
            "promotions:apply",
            // E-commerce orders
            "orders:mark_paid",
            "orders:process",
            "orders:ship",
            "orders:deliver",
            "orders:cancel",
            // Purchasing
            "vendors:create",
            "vendors:read",
            "vendors:update",
            "purchase_orders:create",
            "purchase_orders:read",
            "purchase_orders:update",
            "purchase_orders:submit",
            "purchase_orders:approve",
            "purchase_orders:cancel",
            "purchase_orders:close",
            "goods_receipts:create",
            "goods_receipts:read",
            "goods_receipts:confirm",
            "goods_receipts:cancel",
            // Fiscal
            "invoices:create",
            "invoices:read",
            "invoices:void",
            "invoices:report",
            "tax_rates:create",
            "tax_rates:read",
            "tax_rates:update",
            "tax_rates:delete",
            // Payments — store_admin can view gateways and operate transactions
            // (gateway create/update/delete is reserved to super_admin at the
            // handler layer)
            "payment_gateways:read",
            "transactions:create",
            "transactions:read",
            "transactions:refund",
            "transactions:confirm",
            "transactions:reconcile",
            "payouts:read",
            // Shipping (store_admin can configure methods/zones/rates and
            // operate shipments; delivery_providers CUD is super_admin only)
            "shipping:read",
            "shipping:create",
            "shipping:update",
            "shipping:delete",
            "shipments:read",
            "shipments:create",
            "shipments:update",
            "shipments:assign",
            "shipments:cancel",
            "drivers:read",
            "drivers:create",
            "drivers:update",
            "drivers:delete",
            "delivery_providers:read",
            // Catalog (store_admin can fully manage listings + moderate reviews;
            // image_storage_providers CUD stays super_admin-only)
            "catalog:read",
            "catalog:create",
            "catalog:update",
            "catalog:delete",
            "catalog:moderate",
            "image_storage_providers:read",
            // Reports
            "reports:sales",
            "reports:inventory",
            "reports:inventory_history",
            "reports:inventory_valuation",
            "reports:inventory_low_stock",
            "reports:purchases",
        ],
    ),
    // Store manager
    (
        "store_manager",
        &[
            // Identity
            "users:read",
            "users:list",
            "roles:read",
            "roles:list",
            // Stores
            "stores:read",
            // Products
            "products:read",
            "products:update",
            "products:list",
            "variants:create",
            "variants:read",
            "variants:update",
            "recipes:create",
            "recipes:read",
            "recipes:update",
            "recipes:calculate_cost",
            // Inventory
            "inventory:read",
            "inventory:write",
            "inventory:update",
            "inventory:adjust",
            "inventory:approve_adjustments",
            "inventory:transfer",
            "inventory:reserve",
            "reservations:create",
            "reservations:read",
            "reservations:confirm",
            "reservations:cancel",
            "adjustments:create",
            "adjustments:read",
            "adjustments:submit",
            "adjustments:approve",
            "transfers:create",
            "transfers:read",
            "transfers:ship",
            "transfers:receive",
            "transfers:cancel",
            "categories:read",
            "categories:list",
            // Sales
            "sales:create",
            "sales:read",
            "sales:update",
            "sales:void",
            "sales:list",
            "sales:complete",
            "sales:reports",
            "sales:process_payment",
            "sales:apply_discount",
            "sales:create_customer",
            "sales:read_customer",
            "sales:update_customer",
            "sales:manage_shift",
            "sales:read_shift",
            "sales:manage_cart",
            "sales:manage_credit_note",
            "sales:read_credit_note",
            "sales:approve_credit_note",
            // Promotions
            "promotions:create",
            "promotions:read",
            "promotions:update",
            "promotions:apply",
            // E-commerce orders
            "orders:process",
            "orders:ship",
            "orders:deliver",
            "orders:cancel",
            // Purchasing
            "vendors:read",
            "purchase_orders:create",
            "purchase_orders:read",
            "purchase_orders:update",
            "purchase_orders:submit",
            "goods_receipts:create",
            "goods_receipts:read",
            // Fiscal
            "invoices:create",
            "invoices:read",
            "invoices:void",
            "invoices:report",
            "tax_rates:read",
            // Payments — managers process and confirm transactions but don't
            // have reconcile-by-bank-statement (super_admin / store_admin)
            "payment_gateways:read",
            "transactions:create",
            "transactions:read",
            "transactions:refund",
            "transactions:confirm",
            "payouts:read",
            // Shipping (manager runs the day-to-day; cannot delete config)
            "shipping:read",
            "shipments:read",
            "shipments:create",
            "shipments:update",
            "shipments:assign",
            "shipments:cancel",
            "drivers:read",
            "drivers:create",
            "drivers:update",
            "delivery_providers:read",
            // Catalog (manager updates listings + moderates reviews; no delete)
            "catalog:read",
            "catalog:create",
            "catalog:update",
            "catalog:moderate",
            "image_storage_providers:read",
            // Reports
            "reports:sales",
            "reports:inventory",
            "reports:inventory_history",
            "reports:inventory_valuation",
            "reports:inventory_low_stock",
        ],
    ),
    // Cashier
    (
        "cashier",
        &[
            // Products
            "products:read",
            "products:list",
            "variants:read",
            "recipes:read",
            "categories:read",
            "categories:list",
            // Inventory
            "inventory:read",
            "inventory:reserve",
            "reservations:create",
            "reservations:confirm",
            "reservations:cancel",
            // Sales
            "sales:create",
            "sales:read",
            "sales:update",
            "sales:list",
            "sales:complete",
            "sales:process_payment",
            "sales:apply_discount",
            "sales:create_customer",
            "sales:read_customer",
            "sales:update_customer",
            "sales:manage_shift",
            "sales:read_shift",
            "sales:manage_cart",
            "sales:manage_credit_note",
            "sales:read_credit_note",
            // Promotions (read + apply at checkout)
            "promotions:read",
            "promotions:apply",
            // Fiscal (generate invoices at POS)
            "invoices:create",
            "invoices:read",
            "tax_rates:read",
            // Payments — cashier records charges (manual flow leaves them
            // pending for a manager to confirm)
            "payment_gateways:read",
            "transactions:create",
            "transactions:read",
            // Shipping (cashier may issue StorePickup/OwnDelivery shipments at POS)
            "shipping:read",
            "shipments:read",
            "shipments:create",
            "shipments:update",
            "drivers:read",
            // Catalog (read-only; cashier needs it to look up products by slug)
            "catalog:read",
        ],
    ),
    // Inventory clerk
    (
        "inventory_clerk",
        &[
            // Products
            "products:read",
            "products:update",
            "products:list",
            "variants:read",
            "variants:update",
            "recipes:read",
            "categories:read",
            "categories:list",
            // Inventory
            "inventory:read",
            "inventory:write",
            "inventory:update",
            "inventory:adjust",
            "adjustments:create",
            "adjustments:read",
            "adjustments:submit",
            "transfers:read",
            // Purchasing
            "vendors:read",
            "purchase_orders:read",
            "goods_receipts:create",
            "goods_receipts:read",
            "goods_receipts:confirm",
            // Reports
            "reports:inventory",
            "reports:inventory_history",
            "reports:inventory_low_stock",
        ],
    ),
    // Purchasing agent
    (
        "purchasing_agent",
        &[
            // Products
            "products:read",
            "products:list",
            "variants:read",
            "categories:read",
            "categories:list",
            // Inventory
            "inventory:read",
            // Purchasing
            "vendors:create",
            "vendors:read",
            "vendors:update",
            "purchase_orders:create",
            "purchase_orders:read",
            "purchase_orders:update",
            "purchase_orders:submit",
            "goods_receipts:create",
            "goods_receipts:read",
            // Reports
            "reports:purchases",
        ],
    ),
    // Viewer - read only
    (
        "viewer",
        &[
            // Products
            "products:read",
            "products:list",
            "variants:read",
            "recipes:read",
            "categories:read",
            "categories:list",
            // Inventory
            "inventory:read",
            "adjustments:read",
            "transfers:read",
            // Sales
            "sales:read",
            "sales:list",
            "sales:read_customer",
            "sales:read_shift",
            "sales:read_credit_note",
            // Purchasing
            "vendors:read",
            "purchase_orders:read",
            "goods_receipts:read",
            // Promotions
            "promotions:read",
            // Fiscal
            "invoices:read",
            "tax_rates:read",
            // Payments — read-only
            "payment_gateways:read",
            "transactions:read",
            "payouts:read",
            // Shipping read-only
            "shipping:read",
            "shipments:read",
            "drivers:read",
            "delivery_providers:read",
            // Catalog read-only
            "catalog:read",
        ],
    ),
    // Customer - e-commerce user
    (
        "customer",
        &[
            // Products (read-only for browsing)
            "products:read",
            "products:list",
            "variants:read",
            "categories:read",
            "categories:list",
            // Inventory (only to check availability)
            "inventory:read",
            // Shopping
            "cart:view",
            "cart:add",
            "cart:update",
            "cart:remove",
            "cart:checkout",
            "reservations:create",
            "reservations:cancel", // Only own reservations
            "orders:create",
            "orders:view_own",
            "orders:cancel_own",
            // Profile
            "profile:view",
            "profile:update",
            "wishlist:manage",
            "reviews:create",
            "reviews:view",
            // Catalog browsing + reviews + wishlist
            "catalog:read",
            "catalog:review",
        ],
    ),
];

/// Main store: (name, address, is_ecommerce, is_active)
pub const MAIN_STORE: (&str, &str, bool, bool) = (
    "Tienda Principal",
    "Dirección Principal, Ciudad",
    false,
    true,
);

/// Super admin user: (email, username, first_name, last_name, password)
/// Password: SuperAdmin123!
pub const SUPER_ADMIN_USER: (&str, &str, &str, &str, &str) = (
    "admin@pos-ecommerce.com",
    "super_admin",
    "Super",
    "Admin",
    "SuperAdmin123!",
);
